### ISSUE TITLE
Error parsing JUnit report on Azure DevOps

### ISSUE THREAD

**Issue by iPlessmann** [pact-foundation/pact-reference#431] opened 2024-06-03 08:28 UTC
I am using the [Pact Verifier CLI](https://github.com/pact-foundation/pact-reference/tree/master/rust/pact_verifier_cli) version 1.1.2 from my AzDO pipeline, the verifier does provides a flag `--junit` to write the results as a JUnit result, that functionality works and i get the following output:

```
<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite id="0" name="MyService" package="testsuite/MyService" tests="4" errors="0" failures="0" hostname="localhost" timestamp="2024-04-11T08:13:30.445406Z" time="1.512"><testcase name="Verifying a pact between MyService2 and MyService - Get greeting" time="0.599"/><testcase name="Verifying a pact between MyService2 and MyService Given aDifferentProviderState - Get greeting with (mapped) provider state" time="0.303"/><testcase name="Verifying a pact between MyService2 and MyService Given unmappedProviderState - Get greeting with (unmapped) provider state" time="0.296"/><testcase name="Verifying a pact between MyService3 and MyService - Get greeting" time="0.314"/><system-out><![CDATA[The pact at https://my-broker-ngt.pactflow.io/pacts/provider/MyService/consumer/MyService2/pact-version/011feb9507a8b024c73385911395230a1d71b20c is being verified because the pact content belongs to the consumer version matching the following criterion:
    * latest version from the main branch 'myservice-pacts' (27.1.0)
This pact is in pending state for this version of MyService because a successful verification result for MyService has not yet been published. If this verification fails, it will not cause the overall build to fail. Read more at https://docs.pact.io/go/pending

Verifying a pact between [1mMyService2[0m and [1mMyService[0m

  Get greeting (3s 234ms loading, 599ms verification)
    returns a response which
      has status code [1m200[0m ([32mOK[0m)
      includes headers
        "[1mContent-Type[0m" with value "[1mapplication/json[0m" ([32mOK[0m)
      has a matching body ([32mOK[0m)

  Get greeting with (mapped) provider state (3s 234ms loading, 303ms verification)
     Given aDifferentProviderState
    returns a response which
      has status code [1m200[0m ([32mOK[0m)
      includes headers
        "[1mContent-Type[0m" with value "[1mapplication/json[0m" ([32mOK[0m)
      has a matching body ([32mOK[0m)

  Get greeting with (unmapped) provider state (3s 234ms loading, 296ms verification)
     Given unmappedProviderState
    returns a response which
      has status code [1m200[0m ([32mOK[0m)
      includes headers
        "[1mContent-Type[0m" with value "[1mapplication/json[0m" ([32mOK[0m)
      has a matching body ([32mOK[0m)

This pact is still in pending state for MyService as a successful verification result has not yet been published
The pact at https://my-broker-ngt.pactflow.io/pacts/provider/MyService/consumer/MyService3/pact-version/b3934c7708d47b1596480e55c61970a2d31f0e50 is being verified because the pact content belongs to the consumer version matching the following criterion:
    * latest version from the main branch 'myservice-pacts' (27.1.0)
This pact has previously been successfully verified by MyService. If this verification fails, it will fail the build. Read more at https://docs.pact.io/go/pending

Verifying a pact between [1mMyService3[0m and [1mMyService[0m

  Get greeting (3s 234ms loading, 314ms verification)
    returns a response which
      has status code [1m200[0m ([32mOK[0m)
      includes headers
        "[1mContent-Type[0m" with value "[1mapplication/json[0m" ([32mOK[0m)
      has a matching body ([32mOK[0m)

]]></system-out></testsuite></testsuites>
```

But when AzDO has to parse that result, it fails with error: `Error : '', hexadecimal value 0x1B, is an invalid character. Line 5, position 26..`

I think the issue is due to the bold tags used around `MyService`, for example `Verifying a pact between [1mMyService2[0m and [1mMyService[0m` the `[1m` is the culprit i think.

**Comment by YOU54F** [comment] 2024-06-05 14:20
duplicate of https://github.com/pact-foundation/pact-reference/issues/421

workaround in the attached thread, fix should be in the next released version of the verifier cli

**Comment by YOU54F** [comment] 2024-06-14 08:47
now released as https://github.com/pact-foundation/pact-reference/releases/tag/pact_verifier_cli-v1.1.3

@iPlessmann please retest and let us know

**Comment by iPlessmann** [comment] 2024-06-14 09:25
Tested it and it works! Thank you very much

**Comment by YOU54F** [comment] 2024-06-14 12:13
awesome! thanks for letting us know

**Closed** 2024-06-14 12:13 UTC
Labels: smartbear-supported
