### ISSUE TITLE
FFI 'values' matcher doesn't appear to support nesting

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-reference#216] opened 2022-09-21 00:43 UTC
From [slack discussion here](https://pact-foundation.slack.com/archives/C9VBGLUM9/p1663672073793379)

Zebi reported that the following object:
```
{
  "john-doe1": {
    "brown-fox": {
      "jumps": "over",
      "the": "lazy dog"
    }
  },
  "john-doe2": {
    "brown-fox2": {
      "jumps": "over",
      "the": "lazy dog"
    }
  }
}
```

isn't matched by this matcher combination in Pact-JS:
```
Matchers.eachKeyLike(
   "some string", 
   Matchers.eachKeyLike(
      "some-string", 
      Matchers.eachKeyLike(
         "some-string",
         Matchers.string())))
```

The expected behaviour is for the keys to be ignored at each level. The actual behaviour is that the keys are only ignored at the first level.

From the discussion with @uglyog , the problem is likely to lie in the way the FFI sets up the matcher paths. It may also lie in the Pact-JS matcher definition. Here's the definition in Pact-JS:

```
export const eachKeyLike = <T extends AnyTemplate>(
  keyTemplate: string,
  template: T
): Matcher<AnyTemplate> => ({
  'pact:matcher:type': 'values',
  value: {
    [keyTemplate]: template,
  },
});
```

This means that the object that would be passed to the FFI is:
```
// Note, I hand crafted this
{
  'pact:matcher:type': 'values',
  value: {
    'some-string': {
      'pact:matcher:type': 'values',
      value: {
        'some-string': {
          'pact:matcher:type': 'values',
          value: {
            'some-string': {
              'pact:matcher:type': 'type',
              value: 'some string',
            },
          },
        },
      },
    },
  },
}
```

**Comment by rholshausen** [comment] 2022-09-27 06:35
It's not the FFI that is the problem, the above commit adds a test that works as expected. I'll check the matching logic to see if the problem is there.

**Comment by rholshausen** [comment] 2022-09-27 07:02
No, it is the paths that are wrong. It sets up rules as `$['some-string']` and then fails with `Actual map is missing the following keys: some-string`. It should be using `*`.

**Comment by rholshausen** [comment] 2022-09-27 07:52
BTW, the `eachKeyLike` function is incorrectly named. It should be something like `eachValueLike`.

**Comment by zzeebbii** [comment] 2022-09-27 08:39
@rholshausen is it fixed now with your commit? Can I try it or should I wait for some release?

**Comment by rholshausen** [comment] 2022-09-27 22:53
Still some changes are required, I'll get a release out today

**Comment by rholshausen** [comment] 2022-09-28 01:37
Pact FFI Library 0.3.12 is released with the fix

**Comment by mefellows** [comment] 2022-09-28 03:19
Thanks Ron. I'll push out an update to the core today.

I'll separately consider how to evolve the function name based on our (separate) discussion in Slack.

**Comment by TimothyJones** [comment] 2022-09-28 03:21
Haha! I was just reporting this here: https://github.com/pact-foundation/pact-js/issues/952

**Closed** 2022-11-04 03:24 UTC
Labels: bug

**Comment by rholshausen** [comment] 2023-03-28 23:35
@eburi `eachKeyLike` is meant to set matchers on the keys which are strings. I think the actual error is being able to specify 
```
eachKeyLike(
    'CLASSIC',
    {
        angebotStatusTechnisch: string('TECHNISCH_KONSISTENT'),
        statusCode: number(100)
    }
),
```
where it should only support something like `eachKeyLike(regex('\\w+', 'CLASSIC'))`
